# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - dev
      
 
pr: none

pool:
  name: Azure Pipelines

variables:
  - name: dockerHubServiceConnection
    value: 'dockerhub-anshad09'
  - name: dockerfilePath
    value: 'Dockerfile'
  - name: System.Debug
    value: true


steps:
  - task: Docker@2
    displayName: 'Login to DockerHub'
    inputs:
      command: login
      containerRegistry: $(dockerHubServiceConnection)

  - script: |
      BRANCH=$(Build.SourceBranchName)
      PREFIX=$([ "$BRANCH" = "main" ] && echo "main" || echo "dev")
      DATE=$(date +'%Y.%m.%d')
      TIME=$(date +'%H%M%S')
      TAG="${PREFIX}.${DATE}.${TIME}"
      echo "##vso[task.setvariable variable=tagName]$TAG"
      echo "Using tag: $TAG"
    displayName: 'Set simple calendar version tagName'

  - task: Docker@2
    displayName: 'Build'
    inputs:
      containerRegistry: $(dockerHubServiceConnection)
      repository: anshad09/smp-devops
      command: 'build'
      Dockerfile: $(dockerfilePath)
      buildContext: '.'
      arguments: '--build-arg PORT=$(port)'
      tags: $(tagName)

  - task: Docker@2
    displayName: 'Push'
    inputs:
      containerRegistry: $(dockerHubServiceConnection)
      repository: anshad09/smp-devops
      command: 'push'
      tags: $(tagName)
